version: '4'
services:
  mysql:
    image: mysql
    container_name: onlineShopBackend-mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql