version: '4'
services:
  redis:
    image: redis:7
    container_name: ONS-redis
    ports:
      - "6381:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data
    command: >
      redis-server
      --appendonly yes
      --requirepass password
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru

  db:
    image: postgres:15.0
    container_name: ONS-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ONS-postgres
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql
      - ./volumes/postgres/logs:/logs
    ports:
      - "5433:5432"

  redis-insight:
    image: redis/redisinsight:2.68
    container_name: ONS-redis-insight
    ports:
      - "8001:8001"
    networks:
      - app-network
    depends_on:
      - redis



volumes:
  redis-data:

networks:
  app-network: