version: '4'
services:
  redis:
    image: redis
    container_name: ONS-redis
    ports:
      - "6381:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "password" ]

  db:
    image: postgres:15.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ONS-postgres
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql
      - ./volumes/postgres/logs:/logs
    ports:
      - 5433:5432

volumes:
  redis-data:

networks:
  app-network: