-- INSERT
-- IGNORE INTO category (name) VALUES
--     ('Смартфоны'),
--     ('Ноутбуки'),
--     ('Наушники'),
--     ('Игровые консоли'),
--     ('Телевизоры');
--
-- INSERT
-- IGNORE INTO products (name, description, price, stock_quantity, created_at, category_id)
-- VALUES
--     ('iPhone 15 Pro', 'Флагманский смартфон от Apple с мощным процессором A17 Bionic', 1199.99, 50, NOW(), 1),
--     ('Samsung Galaxy S24', 'Флагманский смартфон от Samsung с улучшенной камерой', 999.99, 40, NOW(), 2),
--     ('MacBook Pro 16', 'Мощный ноутбук Apple с чипом M3 Pro', 2499.99, 20, NOW(), 3),
--     ('Sony WH-1000XM5', 'Беспроводные наушники с активным шумоподавлением', 399.99, 35, NOW(), 4),
--     ('PlayStation 5', 'Игровая консоль нового поколения от Sony', 499.99, 25, NOW(), 5);
--
-- INSERT
-- IGNORE INTO users (email, name, phone_number, password, role) VALUES
--     ('user1@example.com', 'User One', '1234567890', 'password123', 'ADMIN'),
--     ('user2@example.com', 'User Two', '2345678901', 'password123', 'USER'),
--     ('user3@example.com', 'User Three', '3456789012', 'password123', 'USER'),
--     ('user4@example.com', 'User Four', '4567890123', 'password123', 'USER'),
--     ('user5@example.com', 'User Five', '5678901234', 'password123', 'USER');
--
-- INSERT
-- IGNORE INTO cart (user_id) VALUES
--     (1), (2), (3), (4), (5);
--
-- INSERT
-- IGNORE INTO cart_items (cart_id, product_id, quantity)
-- VALUES
--     (1, 1, 2), (1, 2, 1), (2, 3, 5), (3, 4, 3), (4, 5, 4);
--
-- INSERT
-- IGNORE INTO user_orders (user_id, order_status, created_at)
-- VALUES
--     (1, 'PENDING', NOW()), (2, 'PENDING', NOW()), (3, 'COMPLETED', NOW()), (4, 'CANCELLED', NOW()), (5, 'PENDING', NOW());
--
-- INSERT
-- IGNORE INTO order_item (order_id, product_id, quantity)
-- VALUES
--     (1, 1, 2), (1, 2, 1), (2, 3, 3), (3, 4, 1), (3, 5, 2), (4, 6, 1), (5, 7, 2);
